// prisma/seed.ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log("🌱 Starting seed...")

const userId = "demo-user-123"
  
  await prisma.user.upsert({
    where: { id: userId },
    update: {},
    create: {
      id: userId,
      email: "demo@example.com",
      name: "Demo User",
    },
  })

  await prisma.workflow.create({
    data: {
      userId: userId,
      name: "Demo: Email Automation",
      description: "A sample workflow generated by seed.",
      status: "PUBLISHED",
      nodes: {
        create: [
          {
            type: "TRIGGER",
            connectorType: "gmail-new-email",
            positionX: 100,
            positionY: 100,
            config: { subjectFilter: "Urgent" },
          },
          {
            type: "ACTION",
            connectorType: "slack-send-message",
            positionX: 400,
            positionY: 100,
            config: { channelId: "#alerts" },
          },
          {
            type: "ACTION",
            connectorType: "gmail-send-email",
            positionX: 700,
            positionY: 100,
            config: { to: "me@example.com" },
          }
        ]
      }
    }
  })

  console.log("✅ Seed completed successfully.")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })