import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  // Demo workflow template
  await prisma.workflow.create({
    data: {
      name: "Demo: Email Automation",
      description: "A sample workflow generated by seed.",
      nodes: JSON.stringify([...]),
      edges: JSON.stringify([...]),
    }
  })
}

main()
  .catch(e => console.error(e))
  .finally(async () => await prisma.$disconnect())